name: pythonpipeline
on: workflow_dispatch

jobs:
  build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          ref: main

      - name: installing python
        uses: actions/setup-python@v6 
        with:
          python-version: 'pypy3.10' 
        
          

      - name: get pem file
        run: |
          echo "${{secrets.action_key}}" > devops-team.pem
          chmod 400 devops-team6.pem

      - name: cp python
        run:
          scp -o StrictHostKeyChecking=no -i devops-team.pem app.py ec2-user@13.233.159.221:/home/ec2-user/team6

      - name: cp requirement
        run:
          scp -o StrictHostKeyChecking=no -i devops-team.pem requirement.txt ec2-user@13.233.159.221:/home/ec2-user/team6

      - name: run application
        run:
          ssh -o StrictHostKeyChecking=no -i devops-team.pem ec2-user@13.233.159.221"cd/home/ec2-user && python3 -m venv virtualenv && source virtualenv/bin/activate && pip3 install -r requirement.txt && python3 app.py"
